// Mocks generated by Mockito 5.0.15 from annotations
// in mobile/test/pages/RegistrationPage/RegistrationPage_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:mobile/services/RegistrationService.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [RegistrationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegistrationService extends _i1.Mock
    implements _i2.RegistrationService {
  MockRegistrationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> register(String? phoneNumber) =>
      (super.noSuchMethod(Invocation.method(#register, [phoneNumber]),
          returnValue: Future<String?>.value()) as _i3.Future<String?>);
  @override
  _i3.Future<bool> registerKeys() =>
      (super.noSuchMethod(Invocation.method(#registerKeys, []),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<_i4.Uint8List> getDevicePassword() =>
      (super.noSuchMethod(Invocation.method(#getDevicePassword, []),
              returnValue: Future<_i4.Uint8List>.value(_i4.Uint8List(0)))
          as _i3.Future<_i4.Uint8List>);
  @override
  _i3.Future<bool> isRegistered() =>
      (super.noSuchMethod(Invocation.method(#isRegistered, []),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  String toString() => super.toString();
}
