// Mocks generated by Mockito 5.0.15 from annotations
// in mobile/test/pages/HomePage/HomePage_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i19;
import 'dart:typed_data' as _i20;

import 'package:crypton/crypton.dart' as _i2;
import 'package:mobile/domain/Chat.dart' as _i4;
import 'package:mobile/domain/Contact.dart' as _i5;
import 'package:mobile/domain/Message.dart' as _i6;
import 'package:mobile/services/BlockedNumbersService.dart' as _i7;
import 'package:mobile/services/ChatService.dart' as _i10;
import 'package:mobile/services/CommunicationService.dart' as _i22;
import 'package:mobile/services/ContactService.dart' as _i11;
import 'package:mobile/services/DatabaseService.dart' as _i3;
import 'package:mobile/services/EncryptionService.dart' as _i8;
import 'package:mobile/services/MediaService.dart' as _i14;
import 'package:mobile/services/MemoryStoreService.dart' as _i15;
import 'package:mobile/services/MessageboxService.dart' as _i17;
import 'package:mobile/services/MessageService.dart' as _i12;
import 'package:mobile/services/NotificationService.dart' as _i16;
import 'package:mobile/services/SettingsService.dart' as _i13;
import 'package:mobile/services/UserService.dart' as _i9;
import 'package:mobile/util/Tuple.dart' as _i21;
import 'package:mockito/mockito.dart' as _i1;
import 'package:synchronized/synchronized.dart' as _i18;
import 'package:web_socket_channel/io.dart' as _i23;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeRSAKeypair_0 extends _i1.Fake implements _i2.RSAKeypair {}

class _FakeDatabaseService_1 extends _i1.Fake implements _i3.DatabaseService {}

class _FakeChat_2 extends _i1.Fake implements _i4.Chat {}

class _FakeContact_3 extends _i1.Fake implements _i5.Contact {}

class _FakeMessage_4 extends _i1.Fake implements _i6.Message {}

class _FakeBlockedNumbersService_5 extends _i1.Fake
    implements _i7.BlockedNumbersService {}

class _FakeEncryptionService_6 extends _i1.Fake
    implements _i8.EncryptionService {}

class _FakeUserService_7 extends _i1.Fake implements _i9.UserService {}

class _FakeChatService_8 extends _i1.Fake implements _i10.ChatService {}

class _FakeContactService_9 extends _i1.Fake implements _i11.ContactService {}

class _FakeMessageService_10 extends _i1.Fake implements _i12.MessageService {}

class _FakeSettingsService_11 extends _i1.Fake implements _i13.SettingsService {
}

class _FakeMediaService_12 extends _i1.Fake implements _i14.MediaService {}

class _FakeMemoryStoreService_13 extends _i1.Fake
    implements _i15.MemoryStoreService {}

class _FakeNotificationService_14 extends _i1.Fake
    implements _i16.NotificationService {}

class _FakeMessageboxService_15 extends _i1.Fake
    implements _i17.MessageboxService {}

class _FakeLock_16 extends _i1.Fake implements _i18.Lock {}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i9.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<String> getPhoneNumber() =>
      (super.noSuchMethod(Invocation.method(#getPhoneNumber, []),
          returnValue: Future<String>.value('')) as _i19.Future<String>);
  @override
  _i19.Future<void> setPhoneNumber(String? phoneNumber) => (super.noSuchMethod(
      Invocation.method(#setPhoneNumber, [phoneNumber]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<String> getDisplayName() =>
      (super.noSuchMethod(Invocation.method(#getDisplayName, []),
          returnValue: Future<String>.value('')) as _i19.Future<String>);
  @override
  _i19.Future<void> setDisplayName(String? displayName) => (super.noSuchMethod(
      Invocation.method(#setDisplayName, [displayName]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<String> getStatus() =>
      (super.noSuchMethod(Invocation.method(#getStatus, []),
          returnValue: Future<String>.value('')) as _i19.Future<String>);
  @override
  _i19.Future<void> setStatus(String? status) => (super.noSuchMethod(
      Invocation.method(#setStatus, [status]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<_i20.Uint8List?> getProfileImage() =>
      (super.noSuchMethod(Invocation.method(#getProfileImage, []),
              returnValue: Future<_i20.Uint8List?>.value())
          as _i19.Future<_i20.Uint8List?>);
  @override
  _i19.Future<void> setProfileImage(_i20.Uint8List? profileImage) =>
      (super.noSuchMethod(Invocation.method(#setProfileImage, [profileImage]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<DateTime?> getBirthday() =>
      (super.noSuchMethod(Invocation.method(#getBirthday, []),
          returnValue: Future<DateTime?>.value()) as _i19.Future<DateTime?>);
  @override
  _i19.Future<void> setBirthday(DateTime? birthday) => (super.noSuchMethod(
      Invocation.method(#setBirthday, [birthday]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<String> getDeviceAuthTokenEncoded() =>
      (super.noSuchMethod(Invocation.method(#getDeviceAuthTokenEncoded, []),
          returnValue: Future<String>.value('')) as _i19.Future<String>);
  @override
  _i19.Future<void> storeRSAKeyPair(_i2.RSAKeypair? rsaKeypair) =>
      (super.noSuchMethod(Invocation.method(#storeRSAKeyPair, [rsaKeypair]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<_i2.RSAKeypair> fetchRSAKeyPair() =>
      (super.noSuchMethod(Invocation.method(#fetchRSAKeyPair, []),
              returnValue: Future<_i2.RSAKeypair>.value(_FakeRSAKeypair_0()))
          as _i19.Future<_i2.RSAKeypair>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i10.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseService get databaseService =>
      (super.noSuchMethod(Invocation.getter(#databaseService),
          returnValue: _FakeDatabaseService_1()) as _i3.DatabaseService);
  @override
  void onChanged(void Function()? cb) =>
      super.noSuchMethod(Invocation.method(#onChanged, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnChanged(void Function()? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnChanged, [cb]),
          returnValueForMissingStub: null);
  @override
  _i19.Future<List<_i4.Chat>> fetchAll() =>
      (super.noSuchMethod(Invocation.method(#fetchAll, []),
              returnValue: Future<List<_i4.Chat>>.value(<_i4.Chat>[]))
          as _i19.Future<List<_i4.Chat>>);
  @override
  _i19.Future<_i4.Chat> fetchById(String? chatId) =>
      (super.noSuchMethod(Invocation.method(#fetchById, [chatId]),
              returnValue: Future<_i4.Chat>.value(_FakeChat_2()))
          as _i19.Future<_i4.Chat>);
  @override
  _i19.Future<List<_i21.Tuple<String, String>>> fetchIdsByContactPhoneNumbers(
          List<String>? numbers) =>
      (super.noSuchMethod(
              Invocation.method(#fetchIdsByContactPhoneNumbers, [numbers]),
              returnValue: Future<List<_i21.Tuple<String, String>>>.value(
                  <_i21.Tuple<String, String>>[]))
          as _i19.Future<List<_i21.Tuple<String, String>>>);
  @override
  _i19.Future<List<_i4.Chat>> fetchByChatType(_i4.ChatType? chatType) =>
      (super.noSuchMethod(Invocation.method(#fetchByChatType, [chatType]),
              returnValue: Future<List<_i4.Chat>>.value(<_i4.Chat>[]))
          as _i19.Future<List<_i4.Chat>>);
  @override
  _i19.Future<_i4.Chat> insert(_i4.Chat? chat) =>
      (super.noSuchMethod(Invocation.method(#insert, [chat]),
              returnValue: Future<_i4.Chat>.value(_FakeChat_2()))
          as _i19.Future<_i4.Chat>);
  @override
  _i19.Future<_i4.Chat> update(_i4.Chat? chat) =>
      (super.noSuchMethod(Invocation.method(#update, [chat]),
              returnValue: Future<_i4.Chat>.value(_FakeChat_2()))
          as _i19.Future<_i4.Chat>);
  @override
  _i19.Future<void> deleteById(String? id) => (super.noSuchMethod(
      Invocation.method(#deleteById, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> existsById(String? id) =>
      (super.noSuchMethod(Invocation.method(#existsById, [id]),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<bool> existsByPhoneNumberAndChatType(
          String? phoneNumber, _i4.ChatType? chatType) =>
      (super.noSuchMethod(
          Invocation.method(
              #existsByPhoneNumberAndChatType, [phoneNumber, chatType]),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<String> findIdByPhoneNumberAndChatType(
          String? phoneNumber, _i4.ChatType? chatType) =>
      (super.noSuchMethod(
          Invocation.method(
              #findIdByPhoneNumberAndChatType, [phoneNumber, chatType]),
          returnValue: Future<String>.value('')) as _i19.Future<String>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ContactService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactService extends _i1.Mock implements _i11.ContactService {
  MockContactService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseService get databaseService =>
      (super.noSuchMethod(Invocation.getter(#databaseService),
          returnValue: _FakeDatabaseService_1()) as _i3.DatabaseService);
  @override
  void onChanged(void Function()? cb) =>
      super.noSuchMethod(Invocation.method(#onChanged, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnChanged(void Function()? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnChanged, [cb]),
          returnValueForMissingStub: null);
  @override
  _i19.Future<List<_i5.Contact>> fetchAll() =>
      (super.noSuchMethod(Invocation.method(#fetchAll, []),
              returnValue: Future<List<_i5.Contact>>.value(<_i5.Contact>[]))
          as _i19.Future<List<_i5.Contact>>);
  @override
  _i19.Future<_i5.Contact> fetchByPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(Invocation.method(#fetchByPhoneNumber, [phoneNumber]),
              returnValue: Future<_i5.Contact>.value(_FakeContact_3()))
          as _i19.Future<_i5.Contact>);
  @override
  _i19.Future<_i5.Contact> insert(_i5.Contact? contact) =>
      (super.noSuchMethod(Invocation.method(#insert, [contact]),
              returnValue: Future<_i5.Contact>.value(_FakeContact_3()))
          as _i19.Future<_i5.Contact>);
  @override
  _i19.Future<_i5.Contact> update(_i5.Contact? contact) =>
      (super.noSuchMethod(Invocation.method(#update, [contact]),
              returnValue: Future<_i5.Contact>.value(_FakeContact_3()))
          as _i19.Future<_i5.Contact>);
  @override
  _i19.Future<void> setContactStatus(
          String? contactPhoneNumber, String? status) =>
      (super.noSuchMethod(
          Invocation.method(#setContactStatus, [contactPhoneNumber, status]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> setContactProfileImage(
          String? contactPhoneNumber, String? profileImage) =>
      (super.noSuchMethod(
              Invocation.method(
                  #setContactProfileImage, [contactPhoneNumber, profileImage]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> setContactBirthday(
          String? contactPhoneNumber, DateTime? birthday) =>
      (super.noSuchMethod(
              Invocation.method(
                  #setContactBirthday, [contactPhoneNumber, birthday]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> deleteByPhoneNumber(String? phoneNumber) => (super
          .noSuchMethod(Invocation.method(#deleteByPhoneNumber, [phoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
      as _i19.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [MessageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageService extends _i1.Mock implements _i12.MessageService {
  MockMessageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseService get databaseService =>
      (super.noSuchMethod(Invocation.getter(#databaseService),
          returnValue: _FakeDatabaseService_1()) as _i3.DatabaseService);
  @override
  _i19.Future<List<_i6.Message>> fetchAllByChatId(String? chatId) =>
      (super.noSuchMethod(Invocation.method(#fetchAllByChatId, [chatId]),
              returnValue: Future<List<_i6.Message>>.value(<_i6.Message>[]))
          as _i19.Future<List<_i6.Message>>);
  @override
  _i19.Future<_i6.Message> fetchById(String? id) =>
      (super.noSuchMethod(Invocation.method(#fetchById, [id]),
              returnValue: Future<_i6.Message>.value(_FakeMessage_4()))
          as _i19.Future<_i6.Message>);
  @override
  _i19.Future<List<_i6.Message>> fetchAllById(List<String>? ids) =>
      (super.noSuchMethod(Invocation.method(#fetchAllById, [ids]),
              returnValue: Future<List<_i6.Message>>.value(<_i6.Message>[]))
          as _i19.Future<List<_i6.Message>>);
  @override
  _i19.Future<_i6.Message> insert(_i6.Message? message) =>
      (super.noSuchMethod(Invocation.method(#insert, [message]),
              returnValue: Future<_i6.Message>.value(_FakeMessage_4()))
          as _i19.Future<_i6.Message>);
  @override
  _i19.Future<_i6.Message> update(_i6.Message? message) =>
      (super.noSuchMethod(Invocation.method(#update, [message]),
              returnValue: Future<_i6.Message>.value(_FakeMessage_4()))
          as _i19.Future<_i6.Message>);
  @override
  _i19.Future<void> updateMessageContents(
          String? messageId, String? newMessage) =>
      (super.noSuchMethod(
          Invocation.method(#updateMessageContents, [messageId, newMessage]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> setMessageDeleted(String? messageId) => (super.noSuchMethod(
      Invocation.method(#setMessageDeleted, [messageId]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> setMessageReadReceipt(
          String? messageId, _i6.ReadReceipt? readReceipt) =>
      (super.noSuchMethod(
          Invocation.method(#setMessageReadReceipt, [messageId, readReceipt]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> deleteById(String? id) => (super.noSuchMethod(
      Invocation.method(#deleteById, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> deleteAllByChatId(String? chatId) => (super.noSuchMethod(
      Invocation.method(#deleteAllByChatId, [chatId]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> setMessageLiked(String? messageId, bool? liked) => (super
          .noSuchMethod(Invocation.method(#setMessageLiked, [messageId, liked]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
      as _i19.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CommunicationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunicationService extends _i1.Mock
    implements _i22.CommunicationService {
  MockCommunicationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.BlockedNumbersService get blockedNumbersService =>
      (super.noSuchMethod(Invocation.getter(#blockedNumbersService),
              returnValue: _FakeBlockedNumbersService_5())
          as _i7.BlockedNumbersService);
  @override
  _i8.EncryptionService get encryptionService =>
      (super.noSuchMethod(Invocation.getter(#encryptionService),
          returnValue: _FakeEncryptionService_6()) as _i8.EncryptionService);
  @override
  _i9.UserService get userService =>
      (super.noSuchMethod(Invocation.getter(#userService),
          returnValue: _FakeUserService_7()) as _i9.UserService);
  @override
  _i10.ChatService get chatService =>
      (super.noSuchMethod(Invocation.getter(#chatService),
          returnValue: _FakeChatService_8()) as _i10.ChatService);
  @override
  _i11.ContactService get contactService =>
      (super.noSuchMethod(Invocation.getter(#contactService),
          returnValue: _FakeContactService_9()) as _i11.ContactService);
  @override
  _i12.MessageService get messageService =>
      (super.noSuchMethod(Invocation.getter(#messageService),
          returnValue: _FakeMessageService_10()) as _i12.MessageService);
  @override
  _i13.SettingsService get settingsService =>
      (super.noSuchMethod(Invocation.getter(#settingsService),
          returnValue: _FakeSettingsService_11()) as _i13.SettingsService);
  @override
  _i14.MediaService get mediaService =>
      (super.noSuchMethod(Invocation.getter(#mediaService),
          returnValue: _FakeMediaService_12()) as _i14.MediaService);
  @override
  _i15.MemoryStoreService get memoryStoreService => (super.noSuchMethod(
      Invocation.getter(#memoryStoreService),
      returnValue: _FakeMemoryStoreService_13()) as _i15.MemoryStoreService);
  @override
  _i16.NotificationService get notificationService => (super.noSuchMethod(
      Invocation.getter(#notificationService),
      returnValue: _FakeNotificationService_14()) as _i16.NotificationService);
  @override
  _i17.MessageboxService get messageboxService =>
      (super.noSuchMethod(Invocation.getter(#messageboxService),
          returnValue: _FakeMessageboxService_15()) as _i17.MessageboxService);
  @override
  _i18.Lock get communicationLock =>
      (super.noSuchMethod(Invocation.getter(#communicationLock),
          returnValue: _FakeLock_16()) as _i18.Lock);
  @override
  set communicationLock(_i18.Lock? _communicationLock) => super.noSuchMethod(
      Invocation.setter(#communicationLock, _communicationLock),
      returnValueForMissingStub: null);
  @override
  set channelNumber(_i23.IOWebSocketChannel? _channelNumber) =>
      super.noSuchMethod(Invocation.setter(#channelNumber, _channelNumber),
          returnValueForMissingStub: null);
  @override
  set channelAnonymous(_i23.IOWebSocketChannel? _channelAnonymous) => super
      .noSuchMethod(Invocation.setter(#channelAnonymous, _channelAnonymous),
          returnValueForMissingStub: null);
  @override
  set anonymousConnectionId(String? _anonymousConnectionId) =>
      super.noSuchMethod(
          Invocation.setter(#anonymousConnectionId, _anonymousConnectionId),
          returnValueForMissingStub: null);
  @override
  String get anonymousId =>
      (super.noSuchMethod(Invocation.getter(#anonymousId), returnValue: '')
          as String);
  @override
  set anonymousId(String? _anonymousId) =>
      super.noSuchMethod(Invocation.setter(#anonymousId, _anonymousId),
          returnValueForMissingStub: null);
  @override
  set onStopPrivateChat(void Function(String)? _onStopPrivateChat) => super
      .noSuchMethod(Invocation.setter(#onStopPrivateChat, _onStopPrivateChat),
          returnValueForMissingStub: null);
  @override
  set onAcceptPrivateChat(void Function()? _onAcceptPrivateChat) =>
      super.noSuchMethod(
          Invocation.setter(#onAcceptPrivateChat, _onAcceptPrivateChat),
          returnValueForMissingStub: null);
  @override
  bool Function(String) get shouldBlockNotifications =>
      (super.noSuchMethod(Invocation.getter(#shouldBlockNotifications),
              returnValue: (String incomingPhoneNumber) => false)
          as bool Function(String));
  @override
  set shouldBlockNotifications(
          bool Function(String)? _shouldBlockNotifications) =>
      super.noSuchMethod(
          Invocation.setter(
              #shouldBlockNotifications, _shouldBlockNotifications),
          returnValueForMissingStub: null);
  @override
  void onMessage(void Function(_i6.Message)? cb) =>
      super.noSuchMethod(Invocation.method(#onMessage, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnMessage(void Function(_i6.Message)? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnMessage, [cb]),
          returnValueForMissingStub: null);
  @override
  void onDelete(void Function(String)? cb) =>
      super.noSuchMethod(Invocation.method(#onDelete, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnDelete(void Function(String)? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnDelete, [cb]),
          returnValueForMissingStub: null);
  @override
  void onAck(void Function(String)? cb) =>
      super.noSuchMethod(Invocation.method(#onAck, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnAck(void Function(String)? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnAck, [cb]),
          returnValueForMissingStub: null);
  @override
  void onAckSeen(void Function(List<String>)? cb) =>
      super.noSuchMethod(Invocation.method(#onAckSeen, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnAckSeen(void Function(List<String>)? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnAckSeen, [cb]),
          returnValueForMissingStub: null);
  @override
  void onMessageLiked(void Function(String, bool)? cb) =>
      super.noSuchMethod(Invocation.method(#onMessageLiked, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnMessageLiked(void Function(String, bool)? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnMessageLiked, [cb]),
          returnValueForMissingStub: null);
  @override
  void onMessageEdited(void Function(String, String)? cb) =>
      super.noSuchMethod(Invocation.method(#onMessageEdited, [cb]),
          returnValueForMissingStub: null);
  @override
  void disposeOnMessageEdited(void Function(String, String)? cb) =>
      super.noSuchMethod(Invocation.method(#disposeOnMessageEdited, [cb]),
          returnValueForMissingStub: null);
  @override
  _i19.Future<void> registerConnectionForMessagebox(String? mid) =>
      (super.noSuchMethod(
              Invocation.method(#registerConnectionForMessagebox, [mid]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> goOnline() => (super.noSuchMethod(
      Invocation.method(#goOnline, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> sendMessage(_i6.Message? message, _i4.ChatType? chatType,
          String? recipientPhoneNumber, String? repliedMessageId) =>
      (super.noSuchMethod(
              Invocation.method(#sendMessage,
                  [message, chatType, recipientPhoneNumber, repliedMessageId]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendImage(_i6.Message? message, _i4.ChatType? chatType,
          String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(
                  #sendImage, [message, chatType, recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendDelete(
          String? messageId, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendDelete, [messageId, recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendLiked(
          String? messageId, bool? liked, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(
                  #sendLiked, [messageId, liked, recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendEditedMessage(String? messageID, String? newMessage,
          String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendEditedMessage,
                  [messageID, newMessage, recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendOnlineStatus(
          bool? online, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
          Invocation.method(#sendOnlineStatus, [online, recipientPhoneNumber]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> sendStatus(String? status, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendStatus, [status, recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendBirthday(int? birthday, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
          Invocation.method(#sendBirthday, [birthday, recipientPhoneNumber]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> sendProfileImage(
          String? profileImageBase64, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
          Invocation.method(
              #sendProfileImage, [profileImageBase64, recipientPhoneNumber]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> sendAck(String? messageId, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendAck, [messageId, recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendAckSeen(
          List<String>? messageIds, String? recipientPhoneNumber) =>
      (super.noSuchMethod(
          Invocation.method(#sendAckSeen, [messageIds, recipientPhoneNumber]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub:
              Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<void> sendRequestStatus(String? contactPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendRequestStatus, [contactPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendRequestBirthday(String? contactPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendRequestBirthday, [contactPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendRequestProfileImage(String? contactPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendRequestProfileImage, [contactPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendStartPrivateChat(String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendStartPrivateChat, [recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendStopPrivateChat(String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendStopPrivateChat, [recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<void> sendAcceptPrivateChat(String? recipientPhoneNumber) =>
      (super.noSuchMethod(
              Invocation.method(#sendAcceptPrivateChat, [recipientPhoneNumber]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<_i22.EventPayload?> getParsedEventPayload(
          Map<String, Object?>? event) =>
      (super.noSuchMethod(Invocation.method(#getParsedEventPayload, [event]),
              returnValue: Future<_i22.EventPayload?>.value())
          as _i19.Future<_i22.EventPayload?>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i13.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<void> setSafeModePin(String? pin) => (super.noSuchMethod(
      Invocation.method(#setSafeModePin, [pin]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getBlurImages() =>
      (super.noSuchMethod(Invocation.method(#getBlurImages, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setBlurImages(bool? value) => (super.noSuchMethod(
      Invocation.method(#setBlurImages, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getSafeMode() =>
      (super.noSuchMethod(Invocation.method(#getSafeMode, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setSafeMode(bool? value) => (super.noSuchMethod(
      Invocation.method(#setSafeMode, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getShareProfilePicture() =>
      (super.noSuchMethod(Invocation.method(#getShareProfilePicture, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setShareProfilePicture(bool? value) => (super.noSuchMethod(
      Invocation.method(#setShareProfilePicture, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getShareStatus() =>
      (super.noSuchMethod(Invocation.method(#getShareStatus, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setShareStatus(bool? value) => (super.noSuchMethod(
      Invocation.method(#setShareStatus, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getShareReadReceipts() =>
      (super.noSuchMethod(Invocation.method(#getShareReadReceipts, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setShareReadReceipts(bool? value) => (super.noSuchMethod(
      Invocation.method(#setShareReadReceipts, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getShareBirthday() =>
      (super.noSuchMethod(Invocation.method(#getShareBirthday, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setShareBirthday(bool? value) => (super.noSuchMethod(
      Invocation.method(#setShareBirthday, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getDisableNotifications() =>
      (super.noSuchMethod(Invocation.method(#getDisableNotifications, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setDisableNotifications(bool? value) => (super.noSuchMethod(
      Invocation.method(#setDisableNotifications, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<bool> getDisableMessagePreview() =>
      (super.noSuchMethod(Invocation.method(#getDisableMessagePreview, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setDisableMessagePreview(bool? value) =>
      (super.noSuchMethod(Invocation.method(#setDisableMessagePreview, [value]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  _i19.Future<bool> getAutoDownloadMedia() =>
      (super.noSuchMethod(Invocation.method(#getAutoDownloadMedia, []),
          returnValue: Future<bool>.value(false)) as _i19.Future<bool>);
  @override
  _i19.Future<void> setAutoDownloadMedia(bool? value) => (super.noSuchMethod(
      Invocation.method(#setAutoDownloadMedia, [value]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i19.Future<void>);
  @override
  _i19.Future<String?> getWallpaperImage() =>
      (super.noSuchMethod(Invocation.method(#getWallpaperImage, []),
          returnValue: Future<String?>.value()) as _i19.Future<String?>);
  @override
  _i19.Future<void> setWallpaperImage(String? imageBase64) =>
      (super.noSuchMethod(Invocation.method(#setWallpaperImage, [imageBase64]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i19.Future<void>);
  @override
  String toString() => super.toString();
}
