package za.ac.up.cs.atbash.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName = "messages")
public class Message {

    private String id;
    private String phoneNumberFrom;
    private String phoneNumberTo;
    private String contents;
    private Date timestamp;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getPhoneNumberFrom() {
        return phoneNumberFrom;
    }

    @DynamoDBAttribute
    public String getPhoneNumberTo() {
        return phoneNumberTo;
    }

    @DynamoDBAttribute
    public String getContents() {
        return contents;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setPhoneNumberFrom(String phoneNumberFrom) {
        this.phoneNumberFrom = phoneNumberFrom;
    }

    public void setPhoneNumberTo(String phoneNumberTo) {
        this.phoneNumberTo = phoneNumberTo;
    }

    public void setContents(String contents) {
        this.contents = contents;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}
