name: deletemessage CI

on:
  pull_request:
    branches: [ development ]
    paths:
    - 'backend/deletemessage/**'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci
        working-directory: backend/deletemessage
      - run: npm test
        working-directory: backend/deletemessage
